sudo: false
language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7-dev
    env: TOXENV=py37
  - python: 3.6
    env: TOXENV=pypi-lint
  - python: 3.6
    env: TOXENV=codestyle
install: pip install tox
before_script:
- cp tests/config-travisci.py config.py
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
