language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
before_script:
- cp errbot/config-travisci.py config.py
- bash test_mypy.sh
install:
- pip install --upgrade pip
- pip install -e .
- pip freeze
sudo: false
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
